export const categories = [
  { id: "all", label: "All" },
  { id: "beer", label: "Beer" },
  { id: "wine", label: "Wine" },
  { id: "whiskey", label: "Whiskey" },
];

export const featuredData = [
  {
    id: "1",
    name: "Premium Wine",
    price: "$44.98",
    volume: "750ml",
    image: "https://via.placeholder.com/70x130.png?text=Wine",
  },
  {
    id: "2",
    name: "Champagne",
    price: "$79.99",
    volume: "1L",
    image: "https://via.placeholder.com/70x130.png?text=Champagne",
  },
  {
    id: "3",
    name: "Scotch Whiskey",
    price: "$20.99",
    volume: "750ml",
    image: "https://via.placeholder.com/70x130.png?text=Scotch",
  },
  {
    id: "4",
    name: "Tequila",
    price: "$45.99",
    volume: "750ml",
    image: "https://via.placeholder.com/70x130.png?text=Tequila",
  },
  {
    id: "5",
    name: "Rum",
    price: "$25.99",
    volume: "750ml",
    image: "https://via.placeholder.com/70x130.png?text=Rum",
  },
];

export const topPicksData = [
  {
    id: "6",
    name: "Premium Wine",
    price: "$44.99",
    volume: "750ml",
    image: "https://via.placeholder.com/70x130.png?text=Wine",
  },
  {
    id: "7",
    name: "Beer",
    price: "$39.99",
    volume: "500ml",
    image: "https://via.placeholder.com/70x130.png?text=Beer",
  },
  {
    id: "8",
    name: "Scotch Whiskey",
    price: "$20.99",
    volume: "750ml",
    image: "https://via.placeholder.com/70x130.png?text=Scotch",
  },
  {
    id: "9",
    name: "Kingfisher",
    price: "$12.99",
    volume: "500ml",
    image: "https://via.placeholder.com/70x130.png?text=Kingfisher",
  },
];

export const savedAddresses = [
  {
    id: "1",
    type: "home",
    label: "Home",
    address: "123, Main Street, Apt 4B New York, NY 10001",
    isPrimary: true,
  },
  {
    id: "2",
    type: "work",
    label: "Work",
    address: "143 Starbridge Drive, Piscataway, NJ 08867, USA",
  },
  {
    id: "3",
    type: "other",
    label: "Glenview Drive",
    address: "28 Glenview Drive, Edison, NJ 08854, USA",
  },
  {
    id: "4",
    type: "other",
    label: "Nimmo Drive",
    address: "208 Nimmo Drive, Oldbridge, NJ 08845, USA",
  },
  {
    id: "5",
    type: "other",
    label: "Beaufin Court",
    address: "118 Beaufin Ct, Westfield, NJ 08876, USA",
  },
];

export const countries = [
  { label: "United States", value: "US" },
  { label: "Canada", value: "CA" },
  { label: "India", value: "IN" },
];

export const states = [
  { label: "New Jersey", value: "US" },
  { label: "Ontario", value: "CA" },
  { label: "Ahmedabad", value: "IN" },
];

export const favouriteProducts = [
  {
    id: "1",
    name: "Dead Man Beer",
    price: "39.98",
    imageUrl: "https://i.imgur.com/1N6J9hR.png",
    isFav: true,
    isAddToCart: true,
  },
  {
    id: "2",
    name: "Vintage Whiskey",
    price: "45.00",
    imageUrl: "https://i.imgur.com/5fVQ1ov.png",
    isFav: true,
    isAddToCart: false,
  },
  {
    id: "3",
    name: "Gin Fizz",
    price: "33.50",
    imageUrl: "https://i.imgur.com/VdK3tMk.png",
    isFav: true,
    isAddToCart: false,
  },
  {
    id: "4",
    name: "Classic Rum",
    price: "29.90",
    imageUrl: "https://i.imgur.com/yhCNQxt.png",
    isFav: true,
    isAddToCart: false,
  },
  {
    id: "5",
    name: "Smooth Tequila",
    price: "51.25",
    imageUrl: "https://i.imgur.com/8lEddqM.png",
    isFav: true,
    isAddToCart: false,
  },
  {
    id: "6",
    name: "Premium Vodka",
    price: "49.00",
    imageUrl: "https://i.imgur.com/V3ylZzG.png",
    isFav: true,
    isAddToCart: false,
  },
  {
    id: "7",
    name: "Red Wine",
    price: "27.30",
    imageUrl: "https://i.imgur.com/X9MRoMs.png",
    isFav: true,
    isAddToCart: false,
  },
  {
    id: "8",
    name: "Sparkling Champagne",
    price: "63.00",
    imageUrl: "https://i.imgur.com/wgdQEPW.png",
    isFav: true,
    isAddToCart: false,
  },
  {
    id: "9",
    name: "Mojito Mix",
    price: "19.75",
    imageUrl: "https://i.imgur.com/3X9z9xH.png",
    isFav: true,
    isAddToCart: false,
  },
  {
    id: "10",
    name: "Craft Beer Pack",
    price: "58.40",
    imageUrl: "https://i.imgur.com/FfsqHd9.png",
    isFav: true,
    isAddToCart: false,
  },
];

export const pastOrderData = [
  {
    id: "1",
    store: "Village Farm",
    location: "NYC, USA",
    items: [
      { name: "Dead Good Beer", price: 47.98, quantity: 1 },
      { name: "Premium Wine", price: 44.98, quantity: 1 },
    ],
    date: "Order placed on 27 Jan, 7:55PM",
    status: "Delivered",
    price: "$105.95",
    subtotal: 92.96,
    tax: 12.99,
    delivery: 10.0,
    total: 115.95,
    orderNumber: "#1234",
    paymentMethod: "Apple Pay Wallet",
    paid: true,
    time: "March 25, 2025 at 07:30 PM",
    phone: "+1 (555)123-456",
    address: "123, Main Street, Apt 4B\nNew York, NY 10001",
  },
  {
    id: "2",
    store: "Village Farm",
    location: "NYC, USA",
    items: [
      { name: "Dead Good Beer", price: 47.98, quantity: 1 },
      { name: "Premium Wine", price: 44.98, quantity: 1 },
    ],
    date: "Order placed on 28 Jan, 8:30PM",
    status: "Delivered",
    price: "$105.95",
    subtotal: 92.96,
    tax: 12.99,
    delivery: 10.0,
    total: 115.95,
    orderNumber: "#1235",
    paymentMethod: "Visa",
    paid: true,
    time: "March 26, 2025 at 06:10 PM",
    phone: "+1 (555)321-654",
    address: "456, Central Ave, Apt 10A\nBrooklyn, NY 11201",
  },
  {
    id: "3",
    store: "Village Farm",
    location: "NYC, USA",
    items: [
      { name: "Dead Good Beer", price: 47.98, quantity: 1 },
      { name: "Premium Wine", price: 44.98, quantity: 1 },
    ],
    date: "Order placed on 29 Jan, 6:45PM",
    status: "Delivered",
    price: "$105.95",
    subtotal: 92.96,
    tax: 12.99,
    delivery: 10.0,
    total: 115.95,
    orderNumber: "#1236",
    paymentMethod: "Mastercard",
    paid: true,
    time: "March 27, 2025 at 05:00 PM",
    phone: "+1 (555)987-321",
    address: "789, Park Ave, Apt 3B\nQueens, NY 11375",
  },
];

export const activeOrders = [
  {
    id: "1",
    store: "Village Farm",
    location: "NJ, USA",
    items: [
      { name: "5 x Corona Beer", price: 60.0, quantity: 1 },
      { name: "1 x Premium Red CWine", price: 20.0, quantity: 1 },
    ],
    date: "Order placed on 5 May, 7:55PM",
    status: "Preparing",
    price: "$80.00",
    subtotal: 80.0,
    tax: 6.5,
    delivery: 5.0,
    total: 91.5,
    orderNumber: "#2001",
    paymentMethod: "PayPal",
    paid: true,
    time: "May 5, 2025 at 07:55 PM",
    phone: "+1 (555)999-888",
    address: "22B, Beer Street, Apt 1A\nJersey City, NJ 07302",
  },
];
