INSERT INTO package (package_name) VALUES ('8.4OZ CAN 24 LS');
INSERT INTO package (package_name) VALUES ('8.4OZ CAN 6/4');
INSERT INTO package (package_name) VALUES ('12OZ CAN 24 LS');
INSERT INTO package (package_name) VALUES ('12OZ CAN 4/6');
INSERT INTO package (package_name) VALUES ('12OZ CAN 2/12');
INSERT INTO package (package_name) VALUES ('11.2OZ NR 4/6');
INSERT INTO package (package_name) VALUES ('12OZ NR 2/12');
INSERT INTO package (package_name) VALUES ('12OZ NR 24 LS');
INSERT INTO package (package_name) VALUES ('12OZ NR 4/6');
INSERT INTO package (package_name) VALUES ('1/2 BBL');
INSERT INTO package (package_name) VALUES ('1/6 BBL');
INSERT INTO package (package_name) VALUES ('24OZ CAN 12 LS');
INSERT INTO package (package_name) VALUES ('11.2OZ CAN 2/12');
INSERT INTO package (package_name) VALUES ('19 LITER KEG');
INSERT INTO package (package_name) VALUES ('12OZ CAN 6/4');
INSERT INTO package (package_name) VALUES ('11.2OZ CAN 4/6');
INSERT INTO package (package_name) VALUES ('19.2OZ CAN 15 LS');
INSERT INTO package (package_name) VALUES ('1/4 BBL');
INSERT INTO package (package_name) VALUES ('16OZ CAN 6/4');
INSERT INTO package (package_name) VALUES ('19.2OZ CAN 12 LS');
INSERT INTO package (package_name) VALUES ('12OZ CAN 15 LS');
INSERT INTO package (package_name) VALUES ('6.5OZ PET 24 LS');
INSERT INTO package (package_name) VALUES ('23.5OZ CAN 12 LS');
INSERT INTO package (package_name) VALUES ('32OZ NR 12 LS');
INSERT INTO package (package_name) VALUES ('320 ML NR 4/6');
INSERT INTO package (package_name) VALUES ('25.4OZ NR 12 LS');
INSERT INTO package (package_name) VALUES ('21.6OZ NR 12 LS');
INSERT INTO package (package_name) VALUES ('12OZ CAN 30 LS');
INSERT INTO package (package_name) VALUES ('12OZ CAN 36 LS');
INSERT INTO package (package_name) VALUES ('12OZ NR 18 LS');
INSERT INTO package (package_name) VALUES ('16OZ ALUM PINT 15 LS');
INSERT INTO package (package_name) VALUES ('16OZ CAN 4/6');
INSERT INTO package (package_name) VALUES ('12OZ CAN 18 LS');
INSERT INTO package (package_name) VALUES ('24OZ CAN 4/3');
INSERT INTO package (package_name) VALUES ('40OZ NR 12 LS');
INSERT INTO package (package_name) VALUES ('7OZ NR 4/6');
INSERT INTO package (package_name) VALUES ('16OZ ALUM PINT 24 LS');
INSERT INTO package (package_name) VALUES ('16OZ ALUM PINT 2/9');
INSERT INTO package (package_name) VALUES ('24OZ NR 12 LS');
INSERT INTO package (package_name) VALUES ('7OZ NR 24 LS');
INSERT INTO package (package_name) VALUES ('16.9OZ NR 20 LS');
INSERT INTO package (package_name) VALUES ('50 LITER BBL');
INSERT INTO package (package_name) VALUES ('750 ML NR 6 LS');
INSERT INTO package (package_name) VALUES ('12OZ NR 6/4');
INSERT INTO package (package_name) VALUES ('9.6OZ NR 4/6');
INSERT INTO package (package_name) VALUES ('400 ML NR 24 LS');
INSERT INTO package (package_name) VALUES ('700 ML NR 12 LS');
INSERT INTO package (package_name) VALUES ('30 LITER BBL');
INSERT INTO package (package_name) VALUES ('25.4OZ CAN 12 LS');
INSERT INTO package (package_name) VALUES ('200 ML PET 24 LS');
INSERT INTO package (package_name) VALUES ('11.2OZ NR 2/12');
INSERT INTO package (package_name) VALUES ('14.9OZ CAN 3/8');
INSERT INTO package (package_name) VALUES ('14.9OZ CAN 6/4');
INSERT INTO package (package_name) VALUES ('11.2OZ NR 6/4');
INSERT INTO package (package_name) VALUES ('22OZ NR 12 LS');
INSERT INTO package (package_name) VALUES ('25.4OZ NR 6 LS');
INSERT INTO package (package_name) VALUES ('16OZ CAN 8/3');
INSERT INTO package (package_name) VALUES ('20 LITER BBL');
INSERT INTO package (package_name) VALUES ('5 LITER CAN 2 LS');
INSERT INTO package (package_name) VALUES ('8.5OZ CAN 2/12');
INSERT INTO package (package_name) VALUES ('1 LITER PET 15 LS');
INSERT INTO package (package_name) VALUES ('1.5 LITER PET 12 LS');
INSERT INTO package (package_name) VALUES ('20 OZ PET 24 LS');
INSERT INTO package (package_name) VALUES ('16.9OZ CAN 6/4');
INSERT INTO package (package_name) VALUES ('16OZ CAN 3/8');
INSERT INTO package (package_name) VALUES ('19.2OZ CAN 24 LS');
INSERT INTO package (package_name) VALUES ('18OZ PET 12 LS');
INSERT INTO package (package_name) VALUES ('12OZ CAN 12 LS');
INSERT INTO package (package_name) VALUES ('22OZ NR 15 LS');
INSERT INTO package (package_name) VALUES ('25OZ CAN 12 LS');
INSERT INTO package (package_name) VALUES ('11.2OZ CAN 6/4');
INSERT INTO package (package_name) VALUES ('11.5OZ NR 2/12');
INSERT INTO package (package_name) VALUES ('11.5OZ NR 4/6');
INSERT INTO package (package_name) VALUES ('16.9 OZ PET 6/4');
INSERT INTO package (package_name) VALUES ('.75 LITER NR 12 LS');
INSERT INTO package (package_name) VALUES ('11.5OZ CAN 4/6');
INSERT INTO package (package_name) VALUES ('11.5OZ CAN 3/8');
INSERT INTO package (package_name) VALUES ('19.2OZ NR 12 LS');
INSERT INTO package (package_name) VALUES ('500 ML CAN 6/4');
INSERT INTO package (package_name) VALUES ('330 ML CAN 3/8');
INSERT INTO package (package_name) VALUES ('500 ML PET 24 LS');
INSERT INTO package (package_name) VALUES ('12OZ CAN 3/8');
INSERT INTO package (package_name) VALUES ('16.9OZ PET 12 LS');
INSERT INTO package (package_name) VALUES ('11.2OZ NR 24 LS');
INSERT INTO package (package_name) VALUES ('24 LITER BBL');
INSERT INTO package (package_name) VALUES ('16OZ CAN 24 LS');
INSERT INTO package (package_name) VALUES ('12OZ NR 20 LS');
INSERT INTO package (package_name) VALUES ('16OZ NR 12 LS');
INSERT INTO package (package_name) VALUES ('.5 LITER PET 35 LS');
INSERT INTO package (package_name) VALUES ('40OZ NR 12 LOOSE');
INSERT INTO package (package_name) VALUES ('250 ML NR 6/4');
INSERT INTO package (package_name) VALUES ('8.5OZ CAN 6/4');
INSERT INTO package (package_name) VALUES ('750 ML NR 12 LS');
INSERT INTO package (package_name) VALUES ('240 ML CAN 6/4');
INSERT INTO package (package_name) VALUES ('330 ML CAN 4/6');
INSERT INTO package (package_name) VALUES ('1.0 LITER PET 12 LS');
INSERT INTO package (package_name) VALUES ('11OZ NR 6/4');
INSERT INTO package (package_name) VALUES ('50 ML PET 12/10');
INSERT INTO package (package_name) VALUES ('16.9OZ PET 4/6');
INSERT INTO package (package_name) VALUES ('7.5OZ CAN 6/4');
INSERT INTO package (package_name) VALUES ('6.7OZ NR 24 LS');
INSERT INTO package (package_name) VALUES ('750 ML NR 8 LS');
INSERT INTO package (package_name) VALUES ('6.7OZ NR 6/4');
INSERT INTO package (package_name) VALUES ('340 ML NR 4/6');
INSERT INTO package (package_name) VALUES ('16.9OZ TETRA 12 LS');
INSERT INTO package (package_name) VALUES ('1.0 LITER NR 12 LS');
INSERT INTO package (package_name) VALUES ('250 ML NR 4/6');
INSERT INTO package (package_name) VALUES ('500 ML NR 24 LS');
INSERT INTO package (package_name) VALUES ('750 ML NR 15 LS');
INSERT INTO package (package_name) VALUES ('7.5OZ CAN 24 LS');
INSERT INTO package (package_name) VALUES ('330 ML NR 4/6');
INSERT INTO package (package_name) VALUES ('200 ML NR 6/4');
INSERT INTO package (package_name) VALUES ('.50 LITER NR 20 LS');
INSERT INTO package (package_name) VALUES ('6.3OZ NR 4/6');
INSERT INTO package (package_name) VALUES ('7.5OZ CAN 3/8');
INSERT INTO package (package_name) VALUES ('850 ML PET 12 LS');
INSERT INTO package (package_name) VALUES ('375 ML NR 24 LS');
INSERT INTO package (package_name) VALUES ('800 ML NR 12 LS');
INSERT INTO package (package_name) VALUES ('500 ML PET 4/6');
INSERT INTO package (package_name) VALUES ('850 ML PET 2/6');
INSERT INTO package (package_name) VALUES ('15.5OZ CAN 12 LS');
INSERT INTO package (package_name) VALUES ('1 LB LOOSE TEA BAG 6 PK');
INSERT INTO package (package_name) VALUES ('75 CT TEA BAG 6 PK');
INSERT INTO package (package_name) VALUES ('24OZ CAN 15 LS');