 INSERT INTO product (product_name, description, brand_id, category_id, tax_category, is_alcoholic, is_gluten_free, is_kosher, is_wine, has_tobacco, has_cannabis, is_returnable, is_perishable, allergen_info, nutritional_info, is_active, created_at, updated_at) VALUES
 ('ALANI ENERGY CHERRY SLUSH', 'ALANI ENERGY CHERRY SLUSH 8.4OZ CAN 24 LS', (SELECT brand_id FROM brand WHERE brand_name = 'ALANI ENERGY'), (SELECT category_id FROM category WHERE category_name = 'Alcoholic Beverages' LIMIT 1), '', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '{}', '{}', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

 INSERT INTO product (product_name, description, brand_id, category_id, tax_category, is_alcoholic, is_gluten_free, is_kosher, is_wine, has_tobacco, has_cannabis, is_returnable, is_perishable, allergen_info, nutritional_info, is_active, created_at, updated_at) VALUES
 ('ALANI ENERGY CHERRY TWIST', 'ALANI ENERGY CHERRY TWIST 12OZ CAN 24 LS', (SELECT brand_id FROM brand WHERE brand_name = 'ALANI ENERGY'), (SELECT category_id FROM category WHERE category_name = 'Alcoholic Beverages' LIMIT 1), '', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '{}', '{}', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

 INSERT INTO product (product_name, description, brand_id, category_id, tax_category, is_alcoholic, is_gluten_free, is_kosher, is_wine, has_tobacco, has_cannabis, is_returnable, is_perishable, allergen_info, nutritional_info, is_active, created_at, updated_at) VALUES
 ('ALANI ENERGY COSMIC STARDUST', 'ALANI ENERGY COSMIC STARDUST 12OZ CAN 24 LS', (SELECT brand_id FROM brand WHERE brand_name = 'ALANI ENERGY'), (SELECT category_id FROM category WHERE category_name = 'Alcoholic Beverages' LIMIT 1), '', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '{}', '{}', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

 INSERT INTO product (product_name, description, brand_id, category_id, tax_category, is_alcoholic, is_gluten_free, is_kosher, is_wine, has_tobacco, has_cannabis, is_returnable, is_perishable, allergen_info, nutritional_info, is_active, created_at, updated_at) VALUES
 ('ALANI ENERGY HAWAIIAN SHAVED ICE', 'ALANI ENERGY HAWAIIAN SHAVED ICE 12OZ CAN 24 LS', (SELECT brand_id FROM brand WHERE brand_name = 'ALANI ENERGY'), (SELECT category_id FROM category WHERE category_name = 'Alcoholic Beverages' LIMIT 1), '', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '{}', '{}', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

 INSERT INTO product (product_name, description, brand_id, category_id, tax_category, is_alcoholic, is_gluten_free, is_kosher, is_wine, has_tobacco, has_cannabis, is_returnable, is_perishable, allergen_info, nutritional_info, is_active, created_at, updated_at) VALUES
 ('ALANI ENERGY JUICY PEACH', 'ALANI ENERGY JUICY PEACH 12OZ CAN 24 LS', (SELECT brand_id FROM brand WHERE brand_name = 'ALANI ENERGY'), (SELECT category_id FROM category WHERE category_name = 'Alcoholic Beverages' LIMIT 1), '', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '{}', '{}', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

 INSERT INTO product (product_name, description, brand_id, category_id, tax_category, is_alcoholic, is_gluten_free, is_kosher, is_wine, has_tobacco, has_cannabis, is_returnable, is_perishable, allergen_info, nutritional_info, is_active, created_at, updated_at) VALUES
 ('ALANI ENERGY KIWI GUAVA', 'ALANI ENERGY KIWI GUAVA 12OZ CAN 24 LS', (SELECT brand_id FROM brand WHERE brand_name = 'ALANI ENERGY'), (SELECT category_id FROM category WHERE category_name = 'Alcoholic Beverages' LIMIT 1), '', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '{}', '{}', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

 INSERT INTO product (product_name, description, brand_id, category_id, tax_category, is_alcoholic, is_gluten_free, is_kosher, is_wine, has_tobacco, has_cannabis, is_returnable, is_perishable, allergen_info, nutritional_info, is_active, created_at, updated_at) VALUES
 ('ALANI ENERGY ORANGE KISS', 'ALANI ENERGY ORANGE KISS 12OZ CAN 24 LS', (SELECT brand_id FROM brand WHERE brand_name = 'ALANI ENERGY'), (SELECT category_id FROM category WHERE category_name = 'Alcoholic Beverages' LIMIT 1), '', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '{}', '{}', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

 INSERT INTO product (product_name, description, brand_id, category_id, tax_category, is_alcoholic, is_gluten_free, is_kosher, is_wine, has_tobacco, has_cannabis, is_returnable, is_perishable, allergen_info, nutritional_info, is_active, created_at, updated_at) VALUES
 ('ALANI ENERGY PINK SLUSH', 'ALANI ENERGY PINK SLUSH 12OZ CAN 24 LS', (SELECT brand_id FROM brand WHERE brand_name = 'ALANI ENERGY'), (SELECT category_id FROM category WHERE category_name = 'Alcoholic Beverages' LIMIT 1), '', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '{}', '{}', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

 INSERT INTO product (product_name, description, brand_id, category_id, tax_category, is_alcoholic, is_gluten_free, is_kosher, is_wine, has_tobacco, has_cannabis, is_returnable, is_perishable, allergen_info, nutritional_info, is_active, created_at, updated_at) VALUES
 ('ALANI ENERGY STRAWBERRY SUNRISE', 'ALANI ENERGY STRAWBERRY SUNRISE 12OZ CAN 24 LS', (SELECT brand_id FROM brand WHERE brand_name = 'ALANI ENERGY'), (SELECT category_id FROM category WHERE category_name = 'Alcoholic Beverages' LIMIT 1), '', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '{}', '{}', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

 INSERT INTO product (product_name, description, brand_id, category_id, tax_category, is_alcoholic, is_gluten_free, is_kosher, is_wine, has_tobacco, has_cannabis, is_returnable, is_perishable, allergen_info, nutritional_info, is_active, created_at, updated_at) VALUES
 ('ALANI ENERGY VARIETY #2', 'ALANI ENERGY VARIETY #2 12OZ CAN 2/12', (SELECT brand_id FROM brand WHERE brand_name = 'ALANI ENERGY'), (SELECT category_id FROM category WHERE category_name = 'Alcoholic Beverages' LIMIT 1), '', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '{}', '{}', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

 INSERT INTO product (product_name, description, brand_id, category_id, tax_category, is_alcoholic, is_gluten_free, is_kosher, is_wine, has_tobacco, has_cannabis, is_returnable, is_perishable, allergen_info, nutritional_info, is_active, created_at, updated_at) VALUES
 ('ALANI ENERGY VARIETY #3', 'ALANI ENERGY VARIETY #3 12OZ CAN 2/12', (SELECT brand_id FROM brand WHERE brand_name = 'ALANI ENERGY'), (SELECT category_id FROM category WHERE category_name = 'Alcoholic Beverages' LIMIT 1), '', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '{}', '{}', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

 INSERT INTO product (product_name, description, brand_id, category_id, tax_category, is_alcoholic, is_gluten_free, is_kosher, is_wine, has_tobacco, has_cannabis, is_returnable, is_perishable, allergen_info, nutritional_info, is_active, created_at, updated_at) VALUES
 ('ALANI ENERGY WATERMELON WAVE', 'ALANI ENERGY WATERMELON WAVE 12OZ CAN 24 LS', (SELECT brand_id FROM brand WHERE brand_name = 'ALANI ENERGY'), (SELECT category_id FROM category WHERE category_name = 'Alcoholic Beverages' LIMIT 1), '', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '{}', '{}', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

 INSERT INTO product (product_name, description, brand_id, category_id, tax_category, is_alcoholic, is_gluten_free, is_kosher, is_wine, has_tobacco, has_cannabis, is_returnable, is_perishable, allergen_info, nutritional_info, is_active, created_at, updated_at) VALUES
 ('ALANI ENERGY WINTER WONDERLAND', 'ALANI ENERGY WINTER WONDERLAND 12OZ CAN 24 LS', (SELECT brand_id FROM brand WHERE brand_name = 'ALANI ENERGY'), (SELECT category_id FROM category WHERE category_name = 'Alcoholic Beverages' LIMIT 1), '', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '{}', '{}', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

 INSERT INTO product (product_name, description, brand_id, category_id, tax_category, is_alcoholic, is_gluten_free, is_kosher, is_wine, has_tobacco, has_cannabis, is_returnable, is_perishable, allergen_info, nutritional_info, is_active, created_at, updated_at) VALUES
 ('ALFA 11.2 OZ NR 4/6', 'ALFA 11.2 OZ NR 4/6', (SELECT brand_id FROM brand WHERE brand_name = 'ALFA'), (SELECT category_id FROM category WHERE category_name = 'Alcoholic Beverages' LIMIT 1), '', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '{}', '{}', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

 INSERT INTO product (product_name, description, brand_id, category_id, tax_category, is_alcoholic, is_gluten_free, is_kosher, is_wine, has_tobacco, has_cannabis, is_returnable, is_perishable, allergen_info, nutritional_info, is_active, created_at, updated_at) VALUES
 ('AMSTEL LIGHT', 'AMSTEL LIGHT 12OZ CAN 2/12', (SELECT brand_id FROM brand WHERE brand_name = 'AMSTEL LIGHT'), (SELECT category_id FROM category WHERE category_name = 'Alcoholic Beverages' LIMIT 1), '', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '{}', '{}', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
